name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [21, 22, 23, 24, 25, 26]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Tests
      run: |
           rebar3 xref
           rebar3 dialyzer
           rebar3 eunit
